version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file output-template.yml

artifacts:
  files:
    - output-template.yml
